# Generated by Django 2.2.7 on 2020-06-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
