# Generated by Django 2.2.7 on 2020-06-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data dodania komentarza'),
        ),
    ]
